// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        sql.NullInt64 `json:"id"`
	CommentID string        `json:"comment_id"`
	UserID    string        `json:"user_id"`
	ParentID  string        `json:"parent_id"`
	Content   string        `json:"content"`
	Type      string        `json:"type"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type Follow struct {
	ID             sql.NullInt64 `json:"id"`
	FollowerFromID string        `json:"follower_from_id"`
	FollowToID     string        `json:"follow_to_id"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	Active         bool          `json:"active"`
}

type HashTag struct {
	ID        sql.NullInt64 `json:"id"`
	HashtagID string        `json:"hashtag_id"`
	Content   string        `json:"content"`
}

type Like struct {
	ID        sql.NullInt64 `json:"id"`
	LikeID    string        `json:"like_id"`
	ParentID  string        `json:"parent_id"`
	UserID    string        `json:"user_id"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	Type      string        `json:"type"`
	Active    bool          `json:"active"`
}

type Photo struct {
	ID        sql.NullInt64 `json:"id"`
	PhotoID   string        `json:"photo_id"`
	PostID    string        `json:"post_id"`
	Url       string        `json:"url"`
	CreatedAt time.Time     `json:"created_at"`
}

type Post struct {
	ID        sql.NullInt64 `json:"id"`
	PostID    string        `json:"post_id"`
	UserID    string        `json:"user_id"`
	Caption   string        `json:"caption"`
	Longitude float64       `json:"longitude"`
	Latitude  float64       `json:"latitude"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type PostsHashtag struct {
	ID        sql.NullInt64 `json:"id"`
	HashtagID string        `json:"hashtag_id"`
	PostID    string        `json:"post_id"`
}

type Tag struct {
	ID     sql.NullInt64  `json:"id"`
	TagID  string         `json:"tag_id"`
	PostID sql.NullString `json:"post_id"`
}

type User struct {
	ID             sql.NullInt64 `json:"id"`
	UserID         string        `json:"user_id"`
	Username       string        `json:"username"`
	SaltedPassword string        `json:"salted_password"`
	FirstName      string        `json:"first_name"`
	LastName       string        `json:"last_name"`
	Bio            string        `json:"bio"`
	AvatarUrl      string        `json:"avatar_url"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}
