// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Connection interface {
	IsConnection()
}

type Edge interface {
	IsEdge()
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type PageInfo struct {
	EndCursor   string `json:"endCursor"`
	HasNextPage string `json:"hasNextPage"`
}

type PaginationInput struct {
	First *int    `json:"first"`
	After *string `json:"after"`
}
